apiVersion: eks.amazonaws.com/v1
kind: IngressClassParams
metadata:
  name: kairos-public
spec:
  scheme: internet-facing
---
apiVersion: networking.k8s.io/v1
kind: IngressClass
metadata:
  name: kairos-public
spec:
  controller: eks.amazonaws.com/alb
  parameters:
    apiGroup: eks.amazonaws.com
    kind: IngressClassParams
    name: kairos-public
