# Utilizado com o chart oficial secrets-store-csi-driver-provider-aws.
secrets-store-csi-driver:
  install: true
  syncSecret:
    enabled: true
  enableSecretRotation: true
  rotationPollInterval: 2m
tolerations:
  - key: CriticalAddonsOnly
    operator: Exists
