apiVersion: v1
kind: Service
metadata:
  name: {{ include "kairos.name" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "kairos.labels" . | nindent 4 }}
spec:
  type: ClusterIP
  selector:
    {{- include "kairos.selectorLabels" . | nindent 4 }}
  ports:
    - name: http
      port: {{ .Values.service.port }}
      targetPort: http
